### ISSUE TITLE
Is it supposed to be print(r.text)?

### ISSUE THREAD

**Issue by CJerome5** [jakemor/hq#2]
When running the new_game.py (and game_over.py), cmd returns back saying: Is this a typo?

```

 File "new_game.py", line 20
    print r.text
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(r.text)?


```

**Comment by jakemor** [comment]
Make sure yoy are on python 2.7 :)

**Comment by CJerome5** [comment]
Thanks for the quick reply. I changed the version of python to 2.7. Know when I run I get this message:



> Traceback(most recent call last):
  File "new_game.py", line 2, in <module>
    import requests, json
ImportError: No module named 

> requests

**Comment by CJerome5** [comment]
Still a little confused. Is this the correct result, from above, after running new_game.py ?
